### ISSUE TITLE
Cannot find rsc/arctic/scissors

### ISSUE THREAD

**Issue by abhayashi** [zdchan/artigrasp#10]
Thank you for the interesting work.
It would be great if you could provide rsc/arctic/scissors as well.

**Comment by zdchan** [comment]
Hi,

Thanks for the interest in our work! As we explained in the supplementary, we excluded the three objects ”scissors”, ”capsule machine”, and ”phone” from our experiments. ”Scissors” is different from all other objects as it cannot be split into a clear base and articulation part and requires in-hand manipulation. ”Phone” and ”capsule machine” have very small and thin articulation parts which cannot be modeled with our method currently. That's why we don't have these three objects.

Best,
Hui

**Comment by abhayashi** [comment]
Thank you for the explanation. I understand.
