### ISSUE TITLE
Question Regarding Dataset Contact Vector

### ISSUE THREAD

**Issue by Chengjing-314** [zdchan/artigrasp#9]
Hello there,

I really like the project and hope you're doing well. I have a question regarding the processing of finger-object contact data in your project.

While browsing through your code, I encountered some confusion regarding how the finger-object contacts are obtained from the original data. Specifically, I noticed that the `contact/seq/` `.npy` file has a shape of `num_frames * 3 * 16`. However, in [this section of the code](https://github.com/zdchan/artigrasp/blob/main/raisimGymTorch/raisimGymTorch/helper/label_gen_final.py#L863), only the first and second elements of the second dimension are compared.

Could you please elaborate on the following points:
1. How did you obtain the contact vector from original sequence?
2. What do the three elements in the second dimension represent?
3. Why are only the first and second elements of the second dimension used in the comparison?
4. What is the significance of the contact vector having a length of 16? Is there a figure I could reference?

Thank you very much for your assistance!

Best regards,  
Chengjing

**Comment by zdchan** [comment]
Hi Chengjing,

Thanks for the interest in our work! We get the contact vectors by calculating the distance between the hand link and objects with such a function. The contact file has the format `num_frames * 3 * 16`, with the first and second elements of the second dimension as the contact with the top and bottom part of the object respectively, and the third element is the contact states with the whole object (either top or bottom). The length of the contact vector is 16 because there are 16 joints/links for MANO hand, 3 for each finger + 1 for the palm. You can check [manotorch](https://github.com/lixiny/manotorch?tab=readme-ov-file#anatomy-loss) for a visualization.

![1722298786674](https://github.com/user-attachments/assets/f7e94139-37a2-45ef-b2bf-1cac987c3f0e)

Please tell us if you have any further questions!

Best,
Hui

**Comment by Chengjing-314** [comment]
Good evening Hui,

Thank you so much for your speedy response!

To clarify, is `lbs_weight` in the code the same as the `mano['weights']` in the  `MANO_LEFT/RIGHT.pkl` file? And is `argmax_lbs` determining which finger the vertices belong to and has shape `(778,)`?

Much appreciated!

Best regards,
Chengjing

**Comment by zdchan** [comment]
Hi Chengjing,

Yes `lbs_weight` is the output of manolayer (a parameter of MANO). I don't exactly remember the shape of `argmax_lbs`  but overall it determines which finger the vertices belong to.

Best,
Hui

**Comment by Chengjing-314** [comment]
Hi Hui,

Thank you for getting back to me. I have a follow-up question for further clarification.

Is it correct to say that lbs_weight (or [th_weights as seen in the code](https://github.com/lixiny/manotorch/blob/master/manotorch/manolayer.py#L80)) is a parameter that is loaded from the MANO_LEFT/RIGHT.pkl file and not an output of the ManoLayer? 

Thank you again for your help!

Best regards,
Chengjing

**Comment by zdchan** [comment]
Hi Chengjing,

It should be the same and you can also get it from manolayer output as it's a feature defined by MANO instead of our code. But I am not 100% sure. You should be able to easily check it but running the code.

Best,
Hui

**Comment by Chengjing-314** [comment]
Hi Hui,

Thank you so much for your help. Based on our discussion and some visualization, I believe lbs_weight is indeed the same as th_weights in the code, which is loaded from the MANO_LEFT/RIGHT.pkl file and represents the Linear Blend Skinning weights.

I'll proceed with this understanding. I'll close the issue now. Thanks again for your help and your time!

Best regards,
Chengjing
